---
kind: "operation"
client: "rug-cli 0.17.1"
editor:
  name: "UpdateTravisMaven"
  group: "atomist-rugs"
  artifact: "travis-editors"
  version: "0.4.0"
  origin:
    repo: "atomist-rugs/travis-editors.git"
    branch: "master"
    sha: "ffa56d6"

